image:
  repository: docker.io/mginfn/openssh-server
  tag: latest
  pullPolicy: IfNotPresent
service:
  port: 30222  
  type: NodePort
ssh:
  port: 2222
  publicKey:
  userName: interlink-user
resources:
  requests:
    cpu: 100m
    memory: 16Mi
    # ephemeral-storage: 1Gi
  limits:
    cpu: 200m
    memory: 32Mi
    # ephemeral-storage: 2Gi