apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}-sshd-nodeport
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    interlink/role: {{ include "gateway.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.publicPort }}
      protocol: TCP
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
    interlink/role: {{ include "gateway.name" . }}

