apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    interlink/role: {{ include "gateway.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.ssh.port }}
      targetPort: {{ .Values.ssh.port }}
      nodePort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
    interlink/role: {{ include "gateway.name" . }}
{{- if .Values.serviceTunnel }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}-service-tunnel
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    interlink/role: {{ include "gateway.name" . }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.serviceTunnel.port }}
      targetPort: {{ .Values.serviceTunnel.port }}
      nodePort: {{ .Values.serviceTunnel.nodePort }}
      protocol: TCP
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
    interlink/role: {{ include "gateway.name" . }}
{{- end }}
