apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bastion.fullname" . }}
  labels:
    {{- include "bastion.labels" . | nindent 4 }}
    interlink/role: {{ include "bastion.name" . }}
data:
  GATEWAY_HOST: "{{ .Values.gateway.host }}"
  GATEWAY_PORT: "{{ .Values.gateway.ssh.port }}"
  GATEWAY_USER: {{ .Values.gateway.ssh.userName }}
  GATEWAY_TUNNEL_PORT: "{{ .Values.tunnel.gatewayPort }}"
  SERVICE_HOST: {{ .Values.tunnel.serviceHost }}
  SERVICE_PORT: "{{ .Values.tunnel.servicePort }}"
