apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    interlink.io/role: {{ include "gateway.name" . }}
data:
  PUBLIC_KEY: {{ .Values.ssh.publicKey }}
  USER_NAME: {{ .Values.ssh.userName }}
