apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    interlink/role: {{ include "gateway.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "gateway.selectorLabels" . | nindent 6 }}
      interlink/role: {{ include "gateway.name" . }}
  template:
    metadata:
      labels:
        {{- include "gateway.labels" . | nindent 8 }}
        interlink/role: {{ include "gateway.name" . }}
    spec:
      containers:
        - name: openssh-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 2222
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Etc/UTC
          envFrom:
            - configMapRef:
                name: {{ include "gateway.fullname" . }}
