apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    interlink/role: {{ include "gateway.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.ssh.port }}
      targetPort: {{ .Values.ssh.port }}
      nodePort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
    interlink/role: {{ include "gateway.name" . }}
{{- if and .Values.tunnel .Values.tunnel.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}-service-{{ .Values.tunnel.service.sourceNodePort }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    interlink/role: {{ include "gateway.name" . }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.tunnel.service.sourcePort }}
      targetPort: {{ .Values.tunnel.service.sourcePort }}
      nodePort: {{ .Values.tunnel.service.sourceNodePort }}
      protocol: TCP
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
    interlink/role: {{ include "gateway.name" . }}
{{- end }}
