apiVersion: v1
kind: Secret
metadata:
  name: bastion-pod-secret
  namespace: default
type: Opaque
data:
  # base64 --wrap 0 /ssh/id_rsa
  SSH_PRIVATE_KEY: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUNGd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFnRUF0bnNGY2dJci8wUU1GYlY4VXNnd3NxSWZXdWtaL3FWbWFzMjhYNGlwRjltSjFyS2oyRGpqCkRpazVsMW1wUkN0d1NZc2wrYU9jdmJCRkxaUW55YkVxSkNvcTVKRm9BbnFYbWs2ZVAvRWMrVFkwV2RhaEd6SDVzTXo3WEMKcW5YbDFRYTIrWDMwNVdsVVRRNVk3Y2VlaktsZ1BEZ20zeFN2ZlhvRjNrOFVRbnFwUmpEb2krejRLN1V4TEVaQ29jYlFHRwprNzcvMmxyWHRlODBlb2RoS1Z5c2hXSkRpUnpvZkZmNUpYdFE1V0l5KzBxVGRWOHJMZ21nT3d3ZXA4QXEzL1Z1ZTEzK2czCnBESkR1ZjZOYVo2SjlrN2ljZ3BnTFE5UDEvWDdpdDhNNzFJSG85RVVoc1hGbi9tdTkzazRlb0xYK2hxNHNaOFlmNjBLcmYKVnptTWQ2ZFIwV3ZzZ1Z2QVAwa243TmJxUDQ1MFJtMnRVOUh3eVhnWjZLMVF0NzBnb1BqMGtYM3Qzc1FxTnYyblliNXVidwpWbC9uUnJEaXFwU3FJYWN6ckwxbWt1Vk9hdXlGajRFNDFRZmtuanhVdlorMEE3dDdJSzBFWUVjTnpPZnprbTR2UEdqN2JjCkx5TTVRSnliSjdmWnJ0ZjVYRldKNlFJdXRnOVVLeWVSUnliMmNRQ1pqQ3ZmMEZFYlNQS3dncG9hZkp2dEhDenBVNUM2cmoKd0xwbDRpcjJWSG1vY1VSRlNLTjl5ejVoMXlNODhHVHc1MXYzNDkrcEp1ejMxSStJRDdPMEErUGJ2aHdmTmtkaUhpVTR0LwpUV281R0l0ZHU4YUVVVnVrV042a2VBVTE4TnpkdDV5MTdlV083Rzl4ZHpFcml4VTZRZ0hNRnpkSXorSTArVVFlL0VVenhOCmNBQUFkUVlvenY5R0tNNy9RQUFBQUhjM05vTFhKellRQUFBZ0VBdG5zRmNnSXIvMFFNRmJWOFVzZ3dzcUlmV3VrWi9xVm0KYXMyOFg0aXBGOW1KMXJLajJEampEaWs1bDFtcFJDdHdTWXNsK2FPY3ZiQkZMWlFueWJFcUpDb3E1SkZvQW5xWG1rNmVQLwpFYytUWTBXZGFoR3pINXNNejdYQ3FuWGwxUWEyK1gzMDVXbFVUUTVZN2NlZWpLbGdQRGdtM3hTdmZYb0YzazhVUW5xcFJqCkRvaSt6NEs3VXhMRVpDb2NiUUdHazc3LzJsclh0ZTgwZW9kaEtWeXNoV0pEaVJ6b2ZGZjVKWHRRNVdJeSswcVRkVjhyTGcKbWdPd3dlcDhBcTMvVnVlMTMrZzNwREpEdWY2TmFaNko5azdpY2dwZ0xROVAxL1g3aXQ4TTcxSUhvOUVVaHNYRm4vbXU5MwprNGVvTFgraHE0c1o4WWY2MEtyZlZ6bU1kNmRSMFd2c2dWdkFQMGtuN05icVA0NTBSbTJ0VTlId3lYZ1o2SzFRdDcwZ29QCmowa1gzdDNzUXFOdjJuWWI1dWJ3VmwvblJyRGlxcFNxSWFjenJMMW1rdVZPYXV5Rmo0RTQxUWZrbmp4VXZaKzBBN3Q3SUsKMEVZRWNOek9memttNHZQR2o3YmNMeU01UUp5Yko3ZlpydGY1WEZXSjZRSXV0ZzlVS3llUlJ5YjJjUUNaakN2ZjBGRWJTUApLd2dwb2FmSnZ0SEN6cFU1QzZyandMcGw0aXIyVkhtb2NVUkZTS045eXo1aDF5TTg4R1R3NTF2MzQ5K3BKdXozMUkrSUQ3Ck8wQStQYnZod2ZOa2RpSGlVNHQvVFdvNUdJdGR1OGFFVVZ1a1dONmtlQVUxOE56ZHQ1eTE3ZVdPN0c5eGR6RXJpeFU2UWcKSE1GemRJeitJMCtVUWUvRVV6eE5jQUFBQURBUUFCQUFBQ0FEUjZrYmpWYmhERjRaSFd0Uy9iZWNITnhTV3dkdlRZWFdsbQp6SDlPL280bzFpN0VCa0czTG5sU21zanZsTEhScWtQRVBFSWNid1hRYlR5cjZIdGxNNERlRGFMWlBHZkdHTlpjT0wrYjJHCkRGV1czaXYwZGlhblFScDFJOHhCQnIxcVpuRys2eENVNTVVWGhMU3hYV1FIaS9FVmx2dzk1ekEzU1B2RGswaUJIVEJkL1cKck1WaHkveWFuNWRNMHdyNFR0c3JxVW9ES1JrZDkySXJqK0pFMENxMTlVVTM1cFpuK0hOeWtQTys5M2wwVzQ3OE5SOVN6bAoxYzRXNE40bWF4SHpwa2NEOGdpTEdoWWg0a3BYT1ViNExjQnRRbmFDK2t2WjVxTHIvYnpQd3ZtMk5laUNkUkRLVGlyR2xsCnNKU1JLWTM3ZlpVTUxiSVlDZzM4TTJ6djFpUGZMdnBBd3FGYjI2cXM2MXVsNEtBR1laK09yT0tvL1RnRmJzY0tZTWlzeFcKbjRhMVE3Q1FXMzUvY2lXZGNkdlhaUnM2bWc3a0xYRTRFdkxSaFd2SnBwVSttTVhsQkxQTTBJcU9RelRDVU1wVWZKTk1KSwo3U1cyMkpxdkc0RG1jMXdhcWF6RWtpbWtWWmVicC94Z2F6T0ZjOWJhcDB1M3NBN1VvSnM0dndReHJxWE9VZndGT1ppQ1FKCm1wR3NNRmV1M0FnUFBYQkNjbjBSUFRKV1kvQlppZHlnRklOQkd3NkdRRG8vUWFRc00ySG1NcnI1TjJJTTJaZkVBL3g1V0cKY1RSanZENXRYQjhkWFJZNGoweE5MMWMzcFF5OUcrVEtkWGh0cTlTeFlHQmhvMEFaN1BxVzhJUVAwa3EvMDJrSEJ2WTAxRQpkQjNNUEdkemlucGVGY3plU3BBQUFCQVFDdzdPTlhtSzZoRldCbDNIaWRCMDBMYnhmMGZmZTd4bkwxK1V4NjJpUmVXT003CmY4UFJXUzhuZHlFOHNhcDhaRFgzUG5yaEtEZDhFRlpJV0Z3SFFNNzNaOVhHVHNCYnRCYnlkbjFRNndzUDVIQVZkYmduaUcKTkhvT0t0UndEcUlnOEYyemNxN1NacmIvTHA5dXhGd2gxVVAvemVCU3kwOXU0d0xTRnc5eHNHMkJkbVQrQkxlQStmVmdEUQpJUDFsR0FINitRNEhVMjNmeU1IWjZ4VGJxN3Y1a0xwTDJiT1REd3lHWHVTaTZDb2xKNTJod3B6Z0JTdVNYcStHajBIUHo3Ckg0YXBsTk9HZXRGa2lZYnRvVkxxZ0doR1h6WVJ0TTVMRjVKaDhHL284a2UrVlE0dUdWS3NrTDhGSmVuRjBtamY1dmhYSzQKWC84ZGtiNjdpcVVFUlFMTkFBQUJBUURoa3RFUk1YSStwV1pSSWFvejA1MUo1Mk16YmltK2RuQlEzVHg5Wjl4SVc4bjBvVQptQTcydEhPamwzWm1LS1pPUmJPamFnbWdsWWliWms3YVErdmlOdEk2N2FteVpQT3F5WmhQNy9lTGlOMzh0VmdUUEM5eS9OClIyaStCYlFzbFR5Qy9ickZTNCt5Y0dhYm1IcXg5dHpXRFExVi9IbC9qK28waFZqekh5SnA3SWY5Tm5sa1A2Nk5sK2oyQisKSUF1aTZVU3RSdHVGQVpCc2tiSHh5ZEYzSmNlSTZnTDdEalZOMnhhczYxeXVHMi9PcG1pL0dXa0dpT1dvdHRhTFpmTXNzawoyNmIrTmpGS3NkdXQ0bndjNWhGZ3Vxa3cwZWR2d1dISlMrZlNiM3BQOVhTSFJtWTd1VitGSnNuWk0wM0FQK3RlamNNc1RXCnBOVjFIYlJVc3FDN1NwQUFBQkFRRFBHQzRjZzVmMXd3NXpTSThJN0lWOExKbE1lTFE1SUtDNkZGUURYcENiTUhLSnZJelAKS1hzc3lKaDFvbENUaHQwVktleUNmUjF6bk4wTFdsUDlMblV2Zkc2VUlaTXN4NUorOXRJL29ua2gydUc1OVhISTluZWRuSwoxWFYrdkJQeWlEQ2V1Ty96ZDNDeXNsckV2TUdSWStXTk5vWExmZGwzM2RoTlVKSjNkVHcwZE85UXQvWkt0MnNPVzhONHdUCmhhRktHZjRnOEIreWtJd0J5eWI3NHRKb0pKMmMzVWFaWlEwVWx6WktKdTVpd2dUVDlrSk9rRDUrWXhrclBGVXBwZDhreXAKL2JOYjhjdmwyV2czNlk0Z3FtbFJQRHFMUVhmMEdPTUErK2NENU40M2JQb2hCdHcyUHVmYUcxWExnNDZNekw0OUdiTmF2bwozSDl1UDc3TlBoMS9BQUFBRldsdWRHVnliR2x1YXkxbllYUmxkMkY1TFd0bGVRRUNBd1FGCi0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bastion-pod-cm
  namespace: default
data:
  GATEWAY_HOST: "131.154.98.72"
  GATEWAY_SSH_PORT: "30222"
  GATEWAY_TUNNEL_PORT: "8181"
  GATEWAY_USER: interlink-user
  REMOVE_SERVICE_HOST: mlaas-inference-service-predictor-00001.mlaas.svc.cluster.local
  REMOVE_SERVICE_PORT: "80"
---
apiVersion: v1
kind: Pod
metadata:
  name: bastion-pod
  namespace: default
  labels:
    interlink/role: bastion
spec:
  containers:
  - name: openssh-client
    image: docker.io/finalgene/openssh:latest
    command: ["/bin/sh", "-c"]
    args:
    - >-
      eval "$(ssh-agent -s)" &&
      echo "$SSH_DEPLOY_KEY" | ssh-add - &&
      ssh -N -R 0.0.0.0:${GATEWAY_TUNNEL_PORT}:${REMOVE_SERVICE_HOST}:${REMOVE_SERVICE_PORT} ${GATEWAY_USER}@${GATEWAY_HOST} -p ${GATEWAY_SSH_PORT}
      # - ssh -N -R 0.0.0.0:8181:mlaas-inference-service-predictor-00001.mlaas.svc.cluster.local:80 interlink-user@131.154.98.72 -p 30222
    resources:
      requests:
        cpu: 100m
        memory: 16Mi
        # ephemeral-storage: 20Gi
      limits:
        cpu: 200m
        memory: 32Gi
        # ephemeral-storage: 20Gi
    env:
      - name: SSH_DEPLOY_KEY
        valueFrom:
          secretKeyRef:
            name: bastion-pod-secret
            key: SSH_PRIVATE_KEY
    envFrom:
      - configMapRef:
          name: bastion-pod-cm                                                          
  restartPolicy: Always
---
