apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-pod-cm
  namespace: default
data:
  PUBLIC_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC2ewVyAiv/RAwVtXxSyDCyoh9a6Rn+pWZqzbxfiKkX2YnWsqPYOOMOKTmXWalEK3BJiyX5o5y9sEUtlCfJsSokKirkkWgCepeaTp4/8Rz5NjRZ1qEbMfmwzPtcKqdeXVBrb5ffTlaVRNDljtx56MqWA8OCbfFK99egXeTxRCeqlGMOiL7PgrtTEsRkKhxtAYaTvv/aWte17zR6h2EpXKyFYkOJHOh8V/kle1DlYjL7SpN1XysuCaA7DB6nwCrf9W57Xf6DekMkO5/o1pnon2TuJyCmAtD0/X9fuK3wzvUgej0RSGxcWf+a73eTh6gtf6Grixnxh/rQqt9XOYx3p1HRa+yBW8A/SSfs1uo/jnRGba1T0fDJeBnorVC3vSCg+PSRfe3exCo2/adhvm5vBWX+dGsOKqlKohpzOsvWaS5U5q7IWPgTjVB+SePFS9n7QDu3sgrQRgRw3M5/OSbi88aPttwvIzlAnJsnt9mu1/lcVYnpAi62D1QrJ5FHJvZxAJmMK9/QURtI8rCCmhp8m+0cLOlTkLquPAumXiKvZUeahxREVIo33LPmHXIzzwZPDnW/fj36km7PfUj4gPs7QD49u+HB82R2IeJTi39NajkYi127xoRRW6RY3qR4BTXw3N23nLXt5Y7sb3F3MSuLFTpCAcwXN0jP4jT5RB78RTPE1w== interlink-gateway-key
  USER_NAME: interlink-user
---
apiVersion: v1
kind: Pod
metadata:
  name: gateway-pod
  namespace: default
  labels:
    interlink.role: gateway
spec:
  containers:
  - name: openssh-server
    # image: lscr.io/linuxserver/openssh-server:latest
    image: docker.io/mginfn/openssh-server:latest
    imagePullPolicy: Always  # IfNotPresent, Always
    resources:
      requests:
        cpu: 100m
        memory: 16Mi
        # ephemeral-storage: 1Gi
      limits:
        cpu: 200m
        memory: 32Mi
        # ephemeral-storage: 2Gi
    env:
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"
      - name: TZ
        value: Etc/UTC
    envFrom:
      - configMapRef:
          name: gateway-pod-cm
    ports:
      - containerPort: 2222
      # - containerPort: 8181
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-pod-sshd-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    interlink/role: gateway
  ports:
  - port: 2222
    targetPort: 2222
    nodePort: 30222
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-pod-tunnel-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    interlink/role: gateway
  ports:
  - port: 8181
    targetPort: 8181
    nodePort: 30181
---