FROM python:3.12.3

# Arguments for the build
# ARG EXAMPLE_ARG=4.0.0

# To avoid interaction with apt-get
ENV DEBIAN_FRONTEND=noninteractive

# Set default shell to /bin/bash
# https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425
SHELL ["/bin/bash", "-euxo", "pipefail", "-c"]

# App packages
RUN apt -y install apt-transport-https
RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4 && \
    chmod 700 get_helm.sh && \
    ./get_helm.sh

# Upgrade pip
RUN python -m pip install --upgrade pip

# Install pip requirements
COPY requirements.txt /tmp/pip-tmp/
RUN pip --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt \
    && rm -rf /tmp/pip-tmp

# Copy application code and data
COPY ./app_build /interlink-kubernetes-plugin

WORKDIR /interlink-kubernetes-plugin

# Note: You can override docker CMD by providing command parameter to either
# docker run or k8s spec.containers.command
CMD ["uvicorn", "main:app", "--host=0.0.0.0", "--port=30400"]
