image:
  repository: docker.io/finalgene/openssh:latest
  tag: latest
  pullPolicy: IfNotPresent
gateway:
  host:
  ssh:
    port: 30222
    privateKey:
    userName: interlink-user
tunnel:
  serviceHost: 
  servicePort: 80
  gatewayPort: 8181
resources:
  requests:
    cpu: 100m
    memory: 16Mi
    # ephemeral-storage: 1Gi
  limits:
    cpu: 200m
    memory: 32Mi
    # ephemeral-storage: 2Gi
