apiVersion: v1
kind: Pod
metadata:
  name: test-pod-pvc
  namespace: default
  annotations:
    # This annotation is used to indicate that the PVC must exist on the remote cluster
    # in the namespace where the pod will be offloaded.
    interlink.io/remote-pvc: my-volume-claim
spec:
  restartPolicy: Never
  containers:
  - name: test-container
    image: busybox
    command: ["sh", "-c", "ls -al /data; sleep 60; echo 'Done!'; exit 0"]
    resources:
      limits:
        memory: "32Mi"
        cpu: "10m"
    volumeMounts:
      - mountPath: "/data"
        name: my-volume
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: my-volume-claim
  nodeSelector:
    type: virtual-kubelet
  tolerations:
  - key: "virtual-node.interlink/no-schedule"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
---
# TODO The PVC must exist in the local cluster othwerwise Kubernetes won't schedule
# TODO the pod on the virtual node, reporting:
# TODO "0/n nodes are available: persistentvolumeclaim "my-volume-claim" not found."
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-volume-claim
  namespace: default
  annotations:
    # This annotation is used to indicate that the PVC should be deleted from the remote cluster
    # when the pod is deleted.
    interlink.io/pvc-retention-policy: delete
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi