apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bastion.fullname" . }}-{{ .Values.tunnel.gateway.host }}-{{ .Values.tunnel.service.gatewayPort }}
  labels:
    {{- include "bastion.labels" . | nindent 4 }}
    interlink/role: {{ include "bastion.name" . }}
type: Opaque
data:
  SSH_PRIVATE_KEY: {{ .Values.tunnel.gateway.ssh.privateKey }}
